// <auto-generated />
using System;
using Datepicker_Service.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Datepicker_Service.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210428140141_initialcreate")]
    partial class initialcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Datepicker_Service.Models.DatepickerAvailabilityDto", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DateUuid")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("DatepickerDateDtoUuid")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserUuid")
                        .HasColumnType("char(36)");

                    b.HasKey("Uuid");

                    b.HasIndex("DatepickerDateDtoUuid");

                    b.ToTable("DatepickerAvailabilityDto");
                });

            modelBuilder.Entity("Datepicker_Service.Models.DatepickerDateDto", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DatePickerUuid")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("DatepickerDtoUuid")
                        .HasColumnType("char(36)");

                    b.HasKey("Uuid");

                    b.HasIndex("DatepickerDtoUuid");

                    b.ToTable("DatepickerDate");
                });

            modelBuilder.Entity("Datepicker_Service.Models.DatepickerDto", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("AuthorUuid")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Location")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Title")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Uuid");

                    b.ToTable("Datepicker");
                });

            modelBuilder.Entity("Datepicker_Service.Models.DatepickerAvailabilityDto", b =>
                {
                    b.HasOne("Datepicker_Service.Models.DatepickerDateDto", null)
                        .WithMany("UserAvailabilities")
                        .HasForeignKey("DatepickerDateDtoUuid");
                });

            modelBuilder.Entity("Datepicker_Service.Models.DatepickerDateDto", b =>
                {
                    b.HasOne("Datepicker_Service.Models.DatepickerDto", null)
                        .WithMany("Dates")
                        .HasForeignKey("DatepickerDtoUuid");
                });
#pragma warning restore 612, 618
        }
    }
}
