CREATE USER 'ehv_auth'@'%' IDENTIFIED BY 'fwef09j2390rfjffasf23fs';
GRANT USAGE ON *.* TO 'ehv_auth'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `ehv_auth`;
GRANT ALL PRIVILEGES ON `ehv\_auth`.* TO 'ehv_auth'@'%';

CREATE USER 'ehv_datepicker'@'%' IDENTIFIED BY 'hf9hjkweahgbfuhf34uifhasuifh';
GRANT USAGE ON *.* TO 'ehv_datepicker'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `ehv_datepicker`;
GRANT ALL PRIVILEGES ON `ehv\_datepicker`.* TO 'ehv_datepicker'@'%';

CREATE USER 'ehv_event'@'%' IDENTIFIED BY 'j09j4klja0943u09jgpokjgerg';
GRANT USAGE ON *.* TO 'ehv_event'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `ehv_event`;
GRANT ALL PRIVILEGES ON `ehv\_event`.* TO 'ehv_event'@'%';

CREATE USER 'ehv_artist'@'%' IDENTIFIED BY 'fheu37fh47h47dh3khhg';
GRANT USAGE ON *.* TO 'ehv_artist'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `ehv_artist`;
GRANT ALL PRIVILEGES ON `ehv\_artist`.* TO 'ehv_artist'@'%';

CREATE USER 'ehv_hobby'@'%' IDENTIFIED BY 'hfhygdye74y4373hdhisie';
GRANT USAGE ON *.* TO 'ehv_hobby'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `ehv_hobby`;
GRANT ALL PRIVILEGES ON `ehv\_hobby`.* TO 'ehv_hobby'@'%';

CREATE USER 'ehv_user'@'%' IDENTIFIED BY 'fj09fjaklj23kfjapdokhrth50';
GRANT USAGE ON *.* TO 'ehv_user'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `ehv_user`;
GRANT ALL PRIVILEGES ON `ehv\_user`.* TO 'ehv_user'@'%';

CREATE USER 'ehv_log'@'%' IDENTIFIED BY 'jfoweijf323r889shdfhasdfh';
GRANT USAGE ON *.* TO 'ehv_log'@'%' REQUIRE NONE WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `ehv_log`;
GRANT ALL PRIVILEGES ON `ehv\_log`.* TO 'ehv_log'@'%';