version: '3.4'

services:
  gateway_service:
    image: ${DOCKER_REGISTRY-}gatewayservice
    build:
      context: .
      dockerfile: Gateway_Service/Dockerfile
    ports:
        - "5000:80"

  file_service:
    image: ${DOCKER_REGISTRY-}fileservice
    build:
      context: .
      dockerfile: File_Service/Dockerfile
    ports:
        - "5001:80"

  clamav:
    container_name: clamav
    image: mkodockx/docker-clamav:buster-slim
    ports:
        - "3310:3310"

  datepicker_service:
    image: ${DOCKER_REGISTRY-}datepickerservice
    build:
      context: .
      dockerfile: Datepicker_Service/Dockerfile


  event_service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  user_service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  email_service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  authentication_service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

