version: '3.4'

services:
  gateway_service:
    image: ${DOCKER_REGISTRY-}gatewayservice
    build:
      context: .
      dockerfile: Gateway_Service/Dockerfile
    ports:
        - "5000:80"

  file_service:
    image: ${DOCKER_REGISTRY-}fileservice
    build:
      context: .
      dockerfile: File_Service/Dockerfile
    ports:
        - "5001:80"

  event_datepicker_service:
    image: ${DOCKER_REGISTRY-}eventdatepickerservice
    build:
      context: .
      dockerfile: Event_Datepicker_Service/Dockerfile
    ports:
        - "5002:80"
