version: '3.4'

services:
  gateway_service:
    image: ${DOCKER_REGISTRY-}gatewayservice
    build:
      context: .
      dockerfile: Gateway_Service/Dockerfile
    ports:
        - "5000:80"

  file_service:
    image: ${DOCKER_REGISTRY-}fileservice
    build:
      context: .
      dockerfile: File_Service/Dockerfile
    ports:
        - "5001:80"

  clamav:
    container_name: clamav
    image: mkodockx/docker-clamav:buster-slim
    ports:
        - "3310:3310"
    
  mariadb:
    image: mariadb:10.2
          environment:
            MYSQL_ROOT_PASSWORD: changeme
            MYSQL_DATABASE: mybb
            MYSQL_USER: mybb
            MYSQL_PASSWORD: changeme
          logging:
            driver: syslog
            options:
              tag: "{{.DaemonName}}(image={{.ImageName}};name={{.Name}};id={{.ID}})"
          networks:
            - backend
          restart: on-failure
          volumes:
           - ${PWD}/mariadb:/var/lib/mysql
  
  datepicker_service:
    image: ${DOCKER_REGISTRY-}datepickerservice
    build:
      context: .
      dockerfile: Datepicker_Service/Dockerfile
    ports:
        - "5002:80"

  event_service:
    image: ${DOCKER_REGISTRY-}eventservice
    build:
      context: .
      dockerfile: Event_Service/Dockerfile
    ports:
        - "5003:80"

  user_service:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: User_Service/Dockerfile
    ports:
        - "5004:80"

  email_service:
    image: ${DOCKER_REGISTRY-}emailservice
    build:
      context: .
      dockerfile: Email_Service/Dockerfile
    ports:
        - "5005:80"

  authentication_service:
    image: ${DOCKER_REGISTRY-}authenticationservice
    build:
      context: .
      dockerfile: Authentication_Service/Dockerfile
    ports:
        - "5006:80"