version: '3.8'

services:
  rabbitmq:
    container_name: rabbitmq
    hostname: rabbitmq
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    healthcheck:
        test: ["CMD", "curl", "-f", "http://rabbitmq:15672"]
        interval: 30s
        timeout: 10s
        retries: 5

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    restart: always
    volumes:
      - mariadb-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
      
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8000:80
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mariadb
    depends_on:
      - mariadb

  gateway_service:
    image: ${DOCKER_REGISTRY-}gatewayservice
    build:
      context: .
      dockerfile: Gateway_Service/Dockerfile
    ports:
        - "5000:80"

  file_service:
    image: ${DOCKER_REGISTRY-}fileservice
    build:
      context: .
      dockerfile: File_Service/Dockerfile
    ports:
        - "5001:80"

  clamav:
    container_name: clamav
    image: mkodockx/docker-clamav:buster-slim
    ports:
        - "3310:3310"
    
  datepicker_service:
    image: ${DOCKER_REGISTRY-}datepickerservice
    build:
      context: .
      dockerfile: Datepicker_Service/Dockerfile
    ports:
        - "5002:80"
    depends_on:
      - rabbitmq

  event_service:
    image: ${DOCKER_REGISTRY-}eventservice
    build:
      context: .
      dockerfile: Event_Service/Dockerfile
    ports:
        - "5003:80"
    depends_on:
      - rabbitmq

  user_service:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: User_Service/Dockerfile
    ports:
        - "5004:80"
    depends_on:
      - rabbitmq

  email_service:
    image: ${DOCKER_REGISTRY-}emailservice
    build:
      context: .
      dockerfile: Email_Service/Dockerfile
    ports:
        - "5005:80"
    depends_on:
      - rabbitmq

  authentication_service:
    image: ${DOCKER_REGISTRY-}authenticationservice
    build:
      context: .
      dockerfile: Authentication_Service/Dockerfile
    ports:
        - "5006:80"
    depends_on:
      - rabbitmq

volumes:
  mariadb-data: