// <auto-generated />
using System;
using File_Service.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace File_Service.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("File_Service.Models.DirectoryDto", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<Guid>("OwnerUuid")
                        .HasColumnType("char(36)");

                    b.Property<string>("Path")
                        .HasColumnType("longtext");

                    b.HasKey("Uuid");

                    b.ToTable("Directory");
                });

            modelBuilder.Entity("File_Service.Models.FileDto", b =>
                {
                    b.Property<Guid>("Uuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("FileType")
                        .HasColumnType("int");

                    b.Property<string>("FullPath")
                        .HasColumnType("longtext");

                    b.Property<Guid>("OwnerUuid")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ParentDirectoryUuid")
                        .HasColumnType("char(36)");

                    b.HasKey("Uuid");

                    b.ToTable("File");
                });
#pragma warning restore 612, 618
        }
    }
}
