name: CI hobby service

on:
  pull_request:
    paths:
      - "Hobby_Service/**"
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Restore dependencies
        run: dotnet restore
        working-directory: Hobby_Service
      - name: Build
        run: dotnet build --no-restore
        working-directory: Hobby_Service
      - name: Test
        run: dotnet test --no-build --verbosity normal
        working-directory: Hobby_Service

    env:
      CI: true
